name: Sync from Bitbucket

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Bitbucket repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git clone --mirror https://bitbucket.org/mffff4/qlyukerbot bitbucket-repo

      - name: Push to GitHub
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd bitbucket-repo
          git remote set-url --push origin https://x-access-token:${GH_TOKEN}@github.com/Mffff4/qlyukerbot.git
          git push --mirror
